---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangman.
--- DateTime: 2021/7/16 11:33
---

---@class ANode
---@field X number
---@field Y number
---@field G number
---@field H number
---@field F number
---@field Parent ANode
---@field Next ANode
---@field NodeType AMapDataType
local ANode = Class("ANode")

function ANode:ctor()
    self.X = 0;
    self.Y = 0;
    self.G = 0;
    self.H = 0;
    self.F = 0;
    self.Parent = nil;
    self.Next = nil;
end

function ANode:Reset()
    self.X = 0;
    self.Y = 0;
    self.G = 0;
    self.H = 0;
    self.F = 0;
    self.Parent = nil;
    self.Next = nil;
end

return ANode


