---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangman.
--- DateTime: 2021/7/16 10:38
---

print("in main lua")

require("Class")
local AStarHelper = require("Game.Base.Astar.AStarHelper")
require("Game.Base.Astar.AMapData")
require("Game.Base.Astar.ANodePool")
require("Game.Base.Astar.Line.AFlydSmooth")
local ANode = require("Game.Base.Astar.ANode")

---StartFindPath
---@param p AstarParam
function StartFindPath(p)
    local width = p.mapDataArr2.Length
    AMapDataManager:SetMapSize(width, width)

    --print("start print data2")
    --for i = 0, p.mapDataArr2.Length - 1 do
    --    for j = 0, p.mapDataArr2[i].Length - 1 do
    --        print(p.mapDataArr2[i][j])
    --    end
    --end
    --print("end print data2")
    for i = 1, 20000 do
        local ANode = ANode.New()
        ANodePoolManager:PushFreeNodeToPool(ANode)
    end
    
    for x = 0, p.mapDataArr2.Length - 1 do
        for y = 0, p.mapDataArr2[x].Length - 1 do
            local n = p.mapDataArr2[x][y]
            if n == 1 then
                AMapDataManager:SetBlock(x, y)
            else
                AMapDataManager:SetNormal(x, y)
            end
        end
    end
    
    ---@type AStarHelper
    local aStarHelper = AStarHelper.New(AMapDataManager)
    local path = aStarHelper:FindPath(p.startX, p.startY, p.endX, p.endY, p.maxStep, p.G, p.ifNum, p.ifFlyd, p.flydNum)

    if path ~= nil then
        p.ctrl.debugGrid:SetItems(path)
    end
    
end

function Test()
    return 1
end